version: "3.7"

services:
    content:
        container_name: content
        restart: always
        build: ./Content
        ports:
            - "4000:3000"
        external_links:
            - mongo

    interaction:
        container_name: interaction
        restart: always
        build: ./Interaction
        ports:
            - "4005:3002"
        external_links:
            - mongo

    user:
        container_name: user
        restart: always
        build: ./User
        ports:
            - "4003:3001"
        external_links:
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "40000:27017"
